$CONSOLE:ONLY
_DEST _CONSOLE

RANDOMIZE TIMER
'SCREEN _NEWIMAGE(120, 30)
TYPE newHighScore
    player AS STRING * 10
    score AS _UNSIGNED LONG
END TYPE
'below example create a string structure for 2 players

DIM user(1 TO 2) AS newHighScore
FOR i = 1 TO 2
    PRINT "Player "; i; " Name : ";
    INPUT user(i).player
    PRINT "Player "; i; " Score : ";
    INPUT user(i).score
NEXT
INPUT "Time limit for the link to be valid (in seconds) : ", t
'####################################################################
'---------------------------DATA STRUCTURE--------------------------
'* Only a "single" string will be passed to server containing all data and authentication
'* First 10 chars/bytes -> random chars
'* Next 10 chars/bytes -> expire time (CODED)
'* Next 2 chars/bytes -> number of players in the board data (CODED)
'* Next 1 char/byte -> game mode (CODED)
'* Next contain board data of players (CODED)
'* Next 16 chars/bytes -> authentication


DIM serverData AS STRING
serverData = generateGarbage(10) 'garbage data to confuse hackers. lol
serverData = serverData + numToCode(getCurrentUnixTime~&+t,10) 'this will our expire time.
serverData = serverData + numToCode(2,2) 'number of players data, in this example, it is 2
serverData = serverData + numToCode(1,1) 'game mode, in this example it is easy mode, that is mode = 1
'main board data stored in NAME1 SCORE1 NAME2 SCORE2.... format. NAME->8 chars/bytes, SCORE->5 chars/bytes
FOR i = 1 TO 2
    serverData = serverData + alphaStringToCode(RTRIM$(user(i).player), 8)
    serverData = serverData + numToCode(user(i).score,5)
NEXT
'adding authentication -> 16 chars/bytes
serverData = serverData + generateNewToken

final_url$ = "ashishkingdom.000webhostapp.com/update_score.php?key="+serverData
PRINT "URL : "
PRINT final_url$
PRINT "key length : ";len(serverData)


'generate a token/hash with a pattern
'Method by Ashish
FUNCTION generateNewToken$ ()
    DIM tokenChar AS STRING * 62
    tokenChar = "0123456789QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm"

    DIM tmp$, x
    FOR i = 1 TO 8
        tmp$ = tmp$ + MID$(tokenChar, INT((RND * 62) + 1), 1)
    NEXT
    FOR i = 1 TO 8
        x = ((((ASC(MID$(tmp$, i, 1)) * 101) + 37) MOD 62) + 1)
        tmp$ = tmp$ + MID$(tokenChar, x, 1)
    NEXT
    generateNewToken$ = tmp$
END FUNCTION

'verify if the hash/token passed is generated by generateNewToken()
'Method by Ashish
FUNCTION verifyToken (t$)
    IF LEN(t$) <> 16 THEN EXIT FUNCTION

    DIM tokenChar AS STRING * 62
    tokenChar = "0123456789QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm"

    DIM tmp$
    tmp$ = MID$(t$, 1, 8)
    FOR i = 1 TO 8
        x = ((((ASC(MID$(tmp$, i, 1)) * 101) + 37) MOD 62) + 1)
        tmp$ = tmp$ + MID$(tokenChar, x, 1)
    NEXT

    verifyToken = (tmp$ = t$)

END FUNCTION

FUNCTION generateGarbage$ (n AS INTEGER)
    DIM tokenChar AS STRING * 62
    tokenChar = "0123456789QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm"

    DIM tmp$
    FOR i = 1 TO n
        tmp$ = tmp$ + MID$(tokenChar, INT((RND * 62) + 1), 1)
    NEXT

    generateGarbage$ = tmp$
END FUNCTION


'pass a string containing only UPPER CASE alphabetical characters
'return a coded string
'Method by Ashish
FUNCTION alphaStringToCode$ (s AS STRING, size AS _UNSIGNED INTEGER)
    DIM alpha_char_table AS STRING * 26, x AS INTEGER, i AS INTEGER, tmp AS STRING
    alpha_char_table = "qPaLzOwKsMxIeJdNcjXmEiSkZo"
	s = UCASE$(s)
    FOR i = 1 TO LEN(s)
        x = ASC(MID$(s, i, 1)) - 64
        tmp = tmp + MID$(alpha_char_table, x, 1)
    NEXT
    IF size > LEN(tmp) THEN
		for i = len(tmp)+1 to size
			'tmp = tmp + STRING$(size - LEN(tmp), _trim$(str$(int(rnd*10))))
			tmp = tmp + _trim$(str$(int(rnd*10)))
		next
    END IF
    alphaStringToCode = tmp
END FUNCTION

'pass a coded string returned by alphaStringToCode$
'returns the original UPPER CASED string
'Method by Ashish
FUNCTION codeToAlphaString$ (c AS STRING)
    DIM alpha_char_table AS STRING * 26, x AS INTEGER, i AS INTEGER, j AS STRING * 1, num as string*10
    alpha_char_table = "qPaLzOwKsMxIeJdNcjXmEiSkZo"
	num  = "0123456789"
    FOR i = 1 TO LEN(c)
        j = MID$(c, i, 1)
        IF instr(num, j)=0 THEN
            x = INSTR(alpha_char_table, j)
            codeToAlphaString$ = codeToAlphaString$ + CHR$(x + 64)
        END IF
    NEXT
END FUNCTION

'pass a 10 digit positive number value
'returns coded string of length max_len representing the same number
'max_len is number of digits the number have, its optional parameter.
'passing max_len value as 0 will make the function to use default length of 10
'Method by Ashish
FUNCTION numToCode$ (n AS _UNSIGNED LONG, max_len as _UNSIGNED integer)
    DIM num_table AS STRING * 30, x AS INTEGER, tmp AS STRING
    num_table = "0qA8dZ7vB1eY3yC6kX5bD9fW2xE4pV"
	if max_len = 0 then max_len = 10
    WHILE n > 0
        x = (n MOD 10)
        n = n \ 10
        tmp = tmp + MID$(num_table, x*3 +int(rnd*3)+1, 1)
    WEND
	if max_len>len(tmp) then
		for i = len(tmp)+1 to max_len
			tmp = tmp + MID$(num_table, 1+int(rnd*3), 1)
		next
	end if
    FOR i = max_len TO 1 STEP -1
        numToCode$ = numToCode$ + MID$(tmp, i, 1)
    NEXT
END FUNCTION

'pass coded string returned by numToCode$
'return the original number
'Method by Ashish
FUNCTION codeToNum~& (c AS STRING)
    DIM num_table AS STRING * 30, x AS _UNSIGNED INTEGER, max_len as _UNSIGNED integer
	if len(c)>10 then max_len = 10 else max_len = len(c)
    num_table = "0qA8dZ7vB1eY3yC6kX5bD9fW2xE4pV"
    FOR x = 1 TO max_len
        codeToNum~& = codeToNum~& * 10 + ((INSTR(num_table, MID$(c, x, 1)) - 1)\3)
    NEXT
END FUNCTION


FUNCTION getCurrentUnixTime~& ()
    DIM t$, client AS INTEGER
    DIM crlf$, request$, t!, a$, a2$
    DIM p1 AS LONG, p2 AS LONG

    client = _OPENCLIENT("TCP/IP:80:ashishkingdom.000webhostapp.com")
    IF client = 0 THEN ? "failed to connect"
    crlf$ = CHR$(13) + CHR$(10)
    request$ = "GET /get_score.php?mode=2 HTTP/1.1" + crlf$
    request$ = request$ + "Host: ashishkingdom.000webhostapp.com" + crlf$ + crlf$
    PUT #client, , request$
    t! = TIMER
	timelimit = 10
    DO
        _DELAY .01
        GET #client, , a2$
        a$ = a$ + a2$
        IF INSTR(a$, crlf$) THEN EXIT DO
        IF TIMER > t! + timelimit THEN disableScoreboard = true: EXIT DO
    LOOP
    CLOSE client

    p1 = INSTR(a$, "<p>")
    IF p1 > 0 THEN
        p2 = INSTR(p1 + 1, a$, "</p>")
        IF p2 = 0 THEN EXIT SUB
    END IF

    t$ = MID$(a$, p1 + 3, p2 - p1 - 3)
    getCurrentUnixTime~& = val(t$)
END SUB

